--
-- View "AQ$MY_QUEUE_TABLE_S"
--
CREATE OR REPLACE FORCE EDITIONABLE VIEW "XX_TANGO"."AQ$MY_QUEUE_TABLE_S" ("QUEUE", "NAME", "ADDRESS", "PROTOCOL", "TRANSFORMATION", "QUEUE_TO_QUEUE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT queue_name QUEUE, name NAME , address ADDRESS , protocol PROTOCOL, trans_name TRANSFORMATION, decode(bitand(SUBSCRIBER_TYPE, 512), 512, 'TRUE', 'FALSE') QUEUE_TO_QUEUE  FROM "AQ$_MY_QUEUE_TABLE_S" s  WHERE (bitand(s.subscriber_type, 1) = 1)  WITH READ ONLY
/