--
-- Table "AQ$_MY_QUEUE_TABLE_S"
--
CREATE TABLE "XX_TANGO"."AQ$_MY_QUEUE_TABLE_S" 
   (	"SUBSCRIBER_ID" NUMBER NOT NULL ENABLE, 
	"QUEUE_NAME" VARCHAR2(128) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NAME" VARCHAR2(512) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"PROTOCOL" NUMBER, 
	"SUBSCRIBER_TYPE" NUMBER, 
	"RULE_NAME" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"TRANS_NAME" VARCHAR2(261) COLLATE "USING_NLS_COMP", 
	"RULESET_NAME" VARCHAR2(261) COLLATE "USING_NLS_COMP", 
	"NEGATIVE_RULESET_NAME" VARCHAR2(261) COLLATE "USING_NLS_COMP", 
	"CREATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"MODIFICATION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"DELETION_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"SCN_AT_REMOVE" NUMBER, 
	"SCN_AT_ADD" NUMBER, 
	 PRIMARY KEY ("SUBSCRIBER_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" USAGE QUEUE
/