--
-- Table "AQ$_JMS_QUEUE_TABLE_H"
--
CREATE TABLE "XX_TANGO"."AQ$_JMS_QUEUE_TABLE_H" 
   (	"MSGID" RAW(16), 
	"SUBSCRIBER#" NUMBER, 
	"NAME" VARCHAR2(512) COLLATE "USING_NLS_COMP", 
	"ADDRESS#" NUMBER, 
	"DEQUEUE_TIME" TIMESTAMP (6), 
	"TRANSACTION_ID" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"DEQUEUE_USER" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"PROPAGATED_MSGID" RAW(16), 
	"RETRY_COUNT" NUMBER, 
	"HINT" ROWID, 
	"SPARE" RAW(16), 
	 PRIMARY KEY ("MSGID", "SUBSCRIBER#", "NAME", "ADDRESS#") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS
/