--
-- Table "AQ$_MY_QUEUE_TABLE_T"
--
CREATE TABLE "XX_TANGO"."AQ$_MY_QUEUE_TABLE_T" 
   (	"NEXT_DATE" TIMESTAMP (6), 
	"TXN_ID" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"MSGID" RAW(16), 
	"ACTION" NUMBER, 
	 PRIMARY KEY ("NEXT_DATE", "TXN_ID", "MSGID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS
/