--
-- Table "MY_QUEUE_TABLE"
--
CREATE TABLE "XX_TANGO"."MY_QUEUE_TABLE" 
   (	"Q_NAME" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"MSGID" RAW(16), 
	"CORRID" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"PRIORITY" NUMBER, 
	"STATE" NUMBER, 
	"DELAY" TIMESTAMP (6), 
	"EXPIRATION" NUMBER, 
	"TIME_MANAGER_INFO" TIMESTAMP (6), 
	"LOCAL_ORDER_NO" NUMBER, 
	"CHAIN_NO" NUMBER, 
	"CSCN" NUMBER, 
	"DSCN" NUMBER, 
	"ENQ_TIME" TIMESTAMP (6), 
	"ENQ_UID" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"ENQ_TID" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"DEQ_TIME" TIMESTAMP (6), 
	"DEQ_UID" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"DEQ_TID" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"RETRY_COUNT" NUMBER, 
	"EXCEPTION_QSCHEMA" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"EXCEPTION_QUEUE" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"STEP_NO" NUMBER, 
	"RECIPIENT_KEY" NUMBER, 
	"DEQUEUE_MSGID" RAW(16), 
	"SENDER_NAME" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"SENDER_ADDRESS" VARCHAR2(1024) COLLATE "USING_NLS_COMP", 
	"SENDER_PROTOCOL" NUMBER, 
	"USER_DATA" "SYS"."AQ$_JMS_TEXT_MESSAGE" , 
	"USER_PROP" "SYS"."ANYDATA" , 
	 PRIMARY KEY ("MSGID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" USAGE QUEUE 
 VARRAY "USER_DATA"."HEADER"."PROPERTIES" STORE AS SECUREFILE LOB
/